# Generated by Django 5.0.3 on 2024-03-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='profile_img/default_user_img.jpg', upload_to='', verbose_name='profile image'),
        ),
    ]
