# Generated by Django 5.0.3 on 2024-03-15 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('foodrecipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.foodrecipes')),
            ],
        ),
    ]
