# Generated by Django 5.0.3 on 2024-03-19 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_foodrecipes_bookmark_foodrecipes_like_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodrecipes",
            name="sumnail",
        ),
        migrations.CreateModel(
            name="FoodRecipeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="post/%Y/%m/%d")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.foodrecipes",
                    ),
                ),
            ],
        ),
    ]
