# Generated by Django 5.0.3 on 2024-03-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_alter_foodrecipes_thumnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="foodrecipes",
            old_name="author",
            new_name="user",
        ),
    ]
